package services

// latinFirstNames lists transliterated Latin-script first names (already lowercased by the normaliser).
//
// Keys must be in NormalizePersianName output form. Genuinely unisex or
// ambiguous names are deliberately absent — they resolve through the LLM
// fallback instead, since a wrong dictionary hit would misgender the
// customer right back into the bug this exists to fix.
var latinFirstNames = map[string]string{
	"ali":      "male",
	"amin":     "male",
	"amir":     "male",
	"arash":    "male",
	"arman":    "male",
	"armin":    "male",
	"babak":    "male",
	"bahar":    "female",
	"bahram":   "male",
	"baran":    "female",
	"behnam":   "male",
	"behzad":   "male",
	"cyrus":    "male",
	"darius":   "male",
	"dariush":  "male",
	"donya":    "female",
	"dorsa":    "female",
	"elena":    "female",
	"elmira":   "female",
	"elnaz":    "female",
	"erfan":    "male",
	"farhad":   "male",
	"farzad":   "male",
	"fateme":   "female",
	"fatemeh":  "female",
	"hamed":    "male",
	"hanieh":   "female",
	"hassan":   "male",
	"hasti":    "female",
	"helia":    "female",
	"hosein":   "male",
	"hossein":  "male",
	"kamran":   "male",
	"kian":     "male",
	"kourosh":  "male",
	"mahdi":    "male",
	"mahsa":    "female",
	"maryam":   "female",
	"mehdi":    "male",
	"milad":    "male",
	"mina":     "female",
	"mitra":    "female",
	"mohamad":  "male",
	"mohammad": "male",
	"nahid":    "female",
	"narges":   "female",
	"nasrin":   "female",
	"nastaran": "female",
	"navid":    "male",
	"nazanin":  "female",
	"neda":     "female",
	"negar":    "female",
	"negin":    "female",
	"niloofar": "female",
	"niloufar": "female",
	"nima":     "male",
	"nooshin":  "female",
	"omid":     "male",
	"payam":    "male",
	"peyman":   "male",
	"pouria":   "male",
	"pouya":    "male",
	"reza":     "male",
	"saeed":    "male",
	"sahar":    "female",
	"samira":   "female",
	"sara":     "female",
	"sarina":   "female",
	"sepideh":  "female",
	"setareh":  "female",
	"setayesh": "female",
	"shima":    "female",
	"shirin":   "female",
	"sina":     "male",
	"taraneh":  "female",
	"tina":     "female",
	"vah":      "male",
	"vahid":    "male",
	"yalda":    "female",
	"yasaman":  "female",
	"yasamin":  "female",
	"yekta":    "female",
	"younes":   "male",
	"yousef":   "male",
	"zahra":    "female",
	"zeinab":   "female",
}
