package services

import (
	"context"
	"encoding/json"
	"fmt"
	"strings"
	"time"

	"backEnd/models"
)

const sizeGuideDiagramStyleBlock = `Minimalist premium fashion size-guide diagram. Technical flat sketch of the garment, front view, centered, on a warm off-white background (#FAF7F2). Thin, clean charcoal-black line art (#2B2B2B), no shading, no texture, no shadows, no model. Elegant measurement dimension lines in a single muted terracotta accent color (#C4754B) with small arrowheads at both ends, placed outside the garment silhouette. Each dimension line is labeled with its Persian measurement name in clean, legible, modern Persian typography (same terracotta color), positioned next to its line without overlapping the garment. Lots of breathing room, balanced composition, high-end boutique aesthetic. Absolutely no other text, letters, numbers, watermarks, or logos anywhere in the image.`

// SizingAgentMeasurement represents one measurement definition generated by the sizing agent.
type SizingAgentMeasurement struct {
	Key                string `json:"key"`
	Label              string `json:"label"`
	BodyGuide          string `json:"body_guide"`
	FitAdvice          string `json:"fit_advice"`
	GarmentMeasurement string `json:"garment_measurement,omitempty"`
}

// SizingAgentResult holds the structured output returned by the sizing agent.
type SizingAgentResult struct {
	Name             string                   `json:"name"`
	Slug             string                   `json:"slug"`
	Measurements     []SizingAgentMeasurement `json:"measurements"`
	GeneralFitGuide  string                   `json:"general_fit_guide"`
	NanoBananaPrompt string                   `json:"nano_banana_prompt"`
	ImagePrompt      string                   `json:"image_prompt,omitempty"`
	// AdminMeasurementGuide is only used while generating a sizing type. It is
	// intentionally not copied to models.SizingType, whose public contract is
	// unchanged; the buyer guide is generated separately below.
	AdminMeasurementGuide string `json:"admin_measurement_guide,omitempty"`
}

// ToMeasurementDefs converts agent measurements to model measurement definitions.
func (r *SizingAgentResult) ToMeasurementDefs() []models.SizingMeasurementDef {
	defs := make([]models.SizingMeasurementDef, len(r.Measurements))
	for i, m := range r.Measurements {
		defs[i] = models.SizingMeasurementDef{
			Key:                m.Key,
			Label:              m.Label,
			BodyGuide:          m.BodyGuide,
			FitAdvice:          m.FitAdvice,
			GarmentMeasurement: m.GarmentMeasurement,
		}
	}
	return defs
}

// SizingAgent researches standard garment measurements and generates diagram prompts.
type SizingAgent struct {
	braveClient *BraveSearchClient
	openRouter  sizingStructuredClient
}

// sizingStructuredClient keeps the two-call orchestration testable without
// changing the shared OpenRouter client or any public sizing APIs.
type sizingStructuredClient interface {
	CallWithSchemaAndModel(context.Context, string, map[string]interface{}, string) (*StructuredResponse, error)
}

// NewSizingAgent creates a new sizing agent instance.
func NewSizingAgent() *SizingAgent {
	return &SizingAgent{
		braveClient: NewBraveSearchClient(),
		openRouter:  NewOpenRouterStructuredClient(),
	}
}

// GenerateSizingResearch is a convenience function that uses default clients.
func GenerateSizingResearch(ctx context.Context, clothingType, styleNotes string) (*SizingAgentResult, error) {
	return GenerateSizingResearchWithModel(ctx, clothingType, styleNotes, "")
}

// GenerateSizingResearchWithModel conducts tailoring research using an optional model override.
func GenerateSizingResearchWithModel(ctx context.Context, clothingType, styleNotes, modelOverride string) (*SizingAgentResult, error) {
	agent := NewSizingAgent()
	return agent.ResearchWithModel(ctx, clothingType, styleNotes, modelOverride)
}

// Research conducts tailoring research and returns standard measurements and diagram prompt.
func (a *SizingAgent) Research(ctx context.Context, clothingType, styleNotes string) (*SizingAgentResult, error) {
	return a.ResearchWithModel(ctx, clothingType, styleNotes, "")
}

// ResearchWithModel conducts tailoring research and returns standard measurements and diagram prompt using the given model.
func (a *SizingAgent) ResearchWithModel(ctx context.Context, clothingType, styleNotes, modelOverride string) (*SizingAgentResult, error) {
	trimmedType := strings.TrimSpace(clothingType)
	if trimmedType == "" {
		return nil, fmt.Errorf("clothing type is required")
	}

	// 1. Gather context using Brave Search if available
	searchContext := a.collectSearchContext(ctx, trimmedType)

	// 2. Resolve model: explicit override > AI settings chat_model > fallback to gpt-4o-mini
	model := ResolveModel(strings.TrimSpace(modelOverride), ResolveModel(ChatModelOverride(ctx), "openai/gpt-4o-mini"))

	// 3. Generate only the garment definitions, admin measuring instructions,
	// and diagram prompt. Keeping the buyer-facing guide out of this response
	// prevents the two audiences from being blended by the model.
	definitionsPrompt := buildSizingAgentPrompt(trimmedType, styleNotes, searchContext)
	definitionsResp, err := a.openRouter.CallWithSchemaAndModel(ctx, definitionsPrompt, sizingAgentSchema(), model)
	if err != nil {
		return nil, fmt.Errorf("failed to generate sizing definitions: %w", err)
	}

	var result SizingAgentResult
	if err := json.Unmarshal([]byte(definitionsResp.Content), &result); err != nil {
		return nil, fmt.Errorf("failed to parse sizing definitions output: %w", err)
	}

	// 4. Generate the buyer guide from an explicit, lossless representation of
	// the measurements just generated. The second schema contains only the
	// guide, so it cannot accidentally replace the definitions or diagram.
	guideInput, err := json.Marshal(sizingBuyerGuideInput{
		ClothingType: trimmedType,
		Name:         result.Name,
		Slug:         result.Slug,
		Measurements: result.Measurements,
	})
	if err != nil {
		return nil, fmt.Errorf("failed to prepare sizing guide input: %w", err)
	}
	guidePrompt := buildBuyerFitGuidePrompt(string(guideInput))
	guideResp, err := a.openRouter.CallWithSchemaAndModel(ctx, guidePrompt, sizingBuyerGuideSchema(), model)
	if err != nil {
		return nil, fmt.Errorf("failed to generate buyer sizing guide: %w", err)
	}

	var guide sizingBuyerGuideOutput
	if err := json.Unmarshal([]byte(guideResp.Content), &guide); err != nil {
		return nil, fmt.Errorf("failed to parse buyer sizing guide output: %w", err)
	}
	result.GeneralFitGuide = guide.GeneralFitGuide

	// Set ImagePrompt alias for convenience
	result.ImagePrompt = result.NanoBananaPrompt

	return &result, nil
}

type sizingBuyerGuideInput struct {
	ClothingType string                   `json:"clothing_type"`
	Name         string                   `json:"name"`
	Slug         string                   `json:"slug"`
	Measurements []SizingAgentMeasurement `json:"measurements"`
}

type sizingBuyerGuideOutput struct {
	GeneralFitGuide string `json:"general_fit_guide"`
}

func (a *SizingAgent) collectSearchContext(ctx context.Context, clothingType string) string {
	if a.braveClient == nil || !a.braveClient.IsAvailable() {
		return "No search engine available. Rely on standard tailoring knowledge."
	}

	searchCtx, cancel := context.WithTimeout(ctx, 10*time.Second)
	defer cancel()

	var snippets []string

	// Search Persian tailoring guides
	faQuery := fmt.Sprintf("%s راهنمای اندازه گیری و جدول سایز لباس استاندارد خیاطی", clothingType)
	if faResults, err := a.braveClient.SearchWeb(searchCtx, faQuery, SearchOptions{Count: 3}); err == nil {
		for _, r := range faResults {
			if r.Snippet != "" {
				snippets = append(snippets, fmt.Sprintf("- [%s]: %s", r.Title, r.Snippet))
			}
		}
	}

	// Search English tailoring guides
	enQuery := fmt.Sprintf("%s garment measurement guide standard tailoring size chart", clothingType)
	if enResults, err := a.braveClient.SearchWeb(searchCtx, enQuery, SearchOptions{Count: 3}); err == nil {
		for _, r := range enResults {
			if r.Snippet != "" {
				snippets = append(snippets, fmt.Sprintf("- [%s]: %s", r.Title, r.Snippet))
			}
		}
	}

	if len(snippets) == 0 {
		return "No external tailoring search results found."
	}
	return strings.Join(snippets, "\n")
}

func sizingAgentSchema() map[string]interface{} {
	return map[string]interface{}{
		"name":   "sizing_definitions_output",
		"strict": true,
		"schema": map[string]interface{}{
			"type": "object",
			"properties": map[string]interface{}{
				"name": map[string]interface{}{
					"type":        "string",
					"description": "Descriptive Persian name for this clothing sizing type, e.g. کت بلیزر زنانه",
				},
				"slug": map[string]interface{}{
					"type":        "string",
					"description": "URL-safe English kebab-case slug, e.g. women-blazer",
				},
				"measurements": map[string]interface{}{
					"type":        "array",
					"description": "5 to 6 essential standard garment measurements for this clothing type",
					"items": map[string]interface{}{
						"type": "object",
						"properties": map[string]interface{}{
							"key": map[string]interface{}{
								"type":        "string",
								"description": "English snake_case key (e.g. chest_width, total_length, shoulder_width, sleeve_length, waist, hip, inseam)",
							},
							"label": map[string]interface{}{
								"type":        "string",
								"description": "Standard Persian label for this measurement (e.g. عرض سینه, قد لباس, عرض شانه, قد آستین, دور کمر)",
							},
							"body_guide": map[string]interface{}{
								"type":        "string",
								"description": "Clear step-by-step Persian instructions on how and where to measure with tape on the human body",
							},
							"fit_advice": map[string]interface{}{
								"type":        "string",
								"description": "Persian advice explaining ease allowance and how flat garment measurement compares to body circumference",
							},
							"garment_measurement": map[string]interface{}{
								"type":        "string",
								"description": "Concise Persian instruction for an administrator measuring this point on the laid-flat garment or size table, including whether it is flat width, circumference, or a length",
							},
						},
						"required":             []string{"key", "label", "body_guide", "fit_advice", "garment_measurement"},
						"additionalProperties": false,
					},
				},
				"admin_measurement_guide": map[string]interface{}{
					"type":        "string",
					"description": "Concise Persian guide for an administrator to lay out the garment, use the size table, and record each listed garment measurement consistently",
				},
				"nano_banana_prompt": map[string]interface{}{
					"type":        "string",
					"description": "English prompt for Nano Banana Pro diagram image generator including exact Persian labels in quotes",
				},
			},
			"required":             []string{"name", "slug", "measurements", "admin_measurement_guide", "nano_banana_prompt"},
			"additionalProperties": false,
		},
	}
}

func buildSizingAgentPrompt(clothingType, styleNotes, searchContext string) string {
	notesSection := "None"
	if strings.TrimSpace(styleNotes) != "" {
		notesSection = styleNotes
	}

	return fmt.Sprintf(`You are an expert master fashion pattern maker, garment sizing specialist, and technical illustrator for an Iranian e-commerce fashion brand.

Clothing Type: %s
Style & Fit Notes: %s

Search & Tailoring Context:
%s

Your task is ONLY to create garment measurement definitions and admin production guidance. Do not write a buyer-facing general fit guide or a field named "general_fit_guide"; that will be generated in a separate second call.
1. Provide a concise, professional Persian display name (name) and an English kebab-case slug (slug).
2. Define exactly 5 to 6 essential measurements that buyers need when purchasing this specific garment.
   For each measurement:
   - "key": concise English snake_case identifier (e.g. chest, waist, sleeve_length, shoulder, total_length, hip, inseam).
   - "label": precise Persian standard tailoring term (e.g. "عرض سینه", "دور کمر", "قد آستین", "عرض شانه", "قد کل").
    - "body_guide": clear, polite Persian guide explaining exactly where to place the tape measure on the body and how to measure (نحوه اندازه‌گیری روی بدن).
    - "fit_advice": practical Persian advice on ease allowance (آزادی لباس), fit differences (e.g. difference between flat garment width and body circumference, loose vs fitted).
    - "garment_measurement": concise Persian instruction for an administrator measuring the physical garment or maintaining the size table. State the exact garment points and whether the value is a flat width, a circumference, or a length; do not confuse this with measuring a person's body.
3. "admin_measurement_guide": a concise Persian guide for laying the garment flat, measuring consistently, and entering the listed values in a size table. This is for administrators, not buyers.
4. "nano_banana_prompt": an English prompt for generating a technical measurement diagram using Nano Banana Pro.
   It MUST strictly follow this exact format:
   First, paste the shared style block verbatim:
   "%s"
   Then, describe the garment silhouette clearly, and list numbered dimension lines with their exact Persian labels in quotes matching the labels in measurements, e.g.:
   "The garment is a [silhouette description]. Draw exactly [N] dimension lines with these exact Persian labels:
   1. A [orientation] line along [location], labeled \"[Exact Persian Label]\"
   2. ... "

Ensure Persian text is written with correct Persian typography and orthography (نیم‌فاصله).
Return valid JSON matching the schema.`,
		clothingType,
		notesSection,
		searchContext,
		sizeGuideDiagramStyleBlock,
	)
}

func sizingBuyerGuideSchema() map[string]interface{} {
	return map[string]interface{}{
		"name":   "sizing_buyer_guide_output",
		"strict": true,
		"schema": map[string]interface{}{
			"type":                 "object",
			"additionalProperties": false,
			"properties": map[string]interface{}{
				"general_fit_guide": map[string]interface{}{
					"type":        "string",
					"description": "Concise, direct, confident Persian buyer guide. Explain primarily how the buyer measures their body for every listed garment measurement, then add only a short fit/ease section.",
				},
			},
			"required": []string{"general_fit_guide"},
		},
	}
}

func buildBuyerFitGuidePrompt(measurementsJSON string) string {
	return fmt.Sprintf(`You are writing the buyer-facing sizing guide for an Iranian fashion e-commerce store.

The following JSON is the exact output of the garment-definition step. Preserve every measurement key and Persian label conceptually; do not invent, remove, rename, or reorder the measurements:
<EXACT_GENERATED_MEASUREMENTS>
%s
</EXACT_GENERATED_MEASUREMENTS>

Write ONLY the value of "general_fit_guide" in concise, direct, confident Persian.
- Focus primarily on how the buyer measures their own body for EACH listed measurement, using the exact Persian labels and the garment-measurement semantics where helpful.
- Tell the buyer where to place the tape, how to hold their body, and whether to measure around the body, across it, or along a length.
- Add only a small final fit section about comparing body measurements with the garment table, ease, and choosing between sizes.
- Do not give administrator instructions, production instructions, a diagram prompt, JSON, headings for fields, or unrelated styling advice.
- Do not claim that a flat garment width equals a body circumference; explain the distinction briefly when relevant.
Return valid JSON matching the schema.`, measurementsJSON)
}
