package services

import (
	"context"
	"encoding/json"
	"fmt"
	"strings"
	"time"

	"backEnd/models"
)

const sizeGuideVectorDiagramStyleBlock = `Minimalist premium fashion size-guide diagram. Technical flat sketch vector of the garment, front view, centered, on a warm off-white background (#FAF7F2). Thin, clean charcoal-black line art (#2B2B2B), vectorized clothes, flat 2D lines, no shading, no realistic fabric texture, no shadows, no model. Elegant measurement dimension lines in a single muted terracotta accent color (#C4754B) with small arrowheads at both ends, placed outside the garment silhouette. Each dimension line is labeled with its Persian measurement name in clean, legible, modern Persian typography (same terracotta color), positioned next to its line without overlapping the garment. Lots of breathing room, balanced composition, high-end boutique aesthetic. Absolutely no other text, letters, numbers, watermarks, or logos anywhere in the image.`

const sizeGuideMannequinDiagramStyleBlock = `High-end luxury fashion studio product photography on an invisible ghost mannequin (hollow-man 3D effect). Real physical garment matching the exact style and fit, with natural 3D volume, authentic fabric texture, realistic drape, seams, and gentle tailoring folds. Front view, perfectly centered on a clean seamless pure white studio background (#FFFFFF) with a subtle, soft natural ground contact shadow underneath. No human model visible; the clothing appears naturally filled in 3D with hollow neck and cuffs showing realistic interior lining. Aligned with Voxcina's refined luxury brand aesthetic: sophisticated midnight navy (#1A3C69) and dark slate accents, elegant studio lighting with soft diffuse highlights and natural depth. Elegant measurement dimension lines in muted terracotta accent color (#C4754B) with small arrowheads, placed clearly outside or alongside the garment to indicate key fit measurements. Each dimension line is labeled with its Persian measurement name in clean, legible, modern Persian typography (terracotta color), positioned next to its line without obscuring the clothing. Crisp commercial e-commerce size guide visual, balanced composition, ultra-clean aesthetic. Absolutely no other text, letters, numbers, watermarks, or logos anywhere in the image.`

// SizingAgentMeasurement represents one measurement definition generated by the sizing agent.
type SizingAgentMeasurement struct {
	Key                string `json:"key"`
	Label              string `json:"label"`
	BodyGuide          string `json:"body_guide"`
	FitAdvice          string `json:"fit_advice"`
	GarmentMeasurement string `json:"garment_measurement,omitempty"`
}

// SizingAgentResult holds the structured output returned by the sizing agent.
type SizingAgentResult struct {
	Name                 string                   `json:"name"`
	Slug                 string                   `json:"slug"`
	Measurements         []SizingAgentMeasurement `json:"measurements"`
	GeneralFitGuide      string                   `json:"general_fit_guide"`
	NanoBananaPrompt     string                   `json:"nano_banana_prompt"`
	ImagePromptVector    string                   `json:"image_prompt_vector,omitempty"`
	ImagePromptMannequin string                   `json:"image_prompt_mannequin,omitempty"`
	ImagePrompt          string                   `json:"image_prompt,omitempty"`
	// AdminMeasurementGuide is only used while generating a sizing type. It is
	// intentionally not copied to models.SizingType, whose public contract is
	// unchanged; the buyer guide is generated separately below.
	AdminMeasurementGuide string `json:"admin_measurement_guide,omitempty"`
}

// DiagramPromptsResult holds the updated diagram prompts for vector and mannequin styles.
type DiagramPromptsResult struct {
	ImagePromptVector    string `json:"image_prompt_vector"`
	ImagePromptMannequin string `json:"image_prompt_mannequin"`
}

// ToMeasurementDefs converts agent measurements to model measurement definitions.
func (r *SizingAgentResult) ToMeasurementDefs() []models.SizingMeasurementDef {
	defs := make([]models.SizingMeasurementDef, len(r.Measurements))
	for i, m := range r.Measurements {
		defs[i] = models.SizingMeasurementDef{
			Key:                m.Key,
			Label:              m.Label,
			BodyGuide:          m.BodyGuide,
			FitAdvice:          m.FitAdvice,
			GarmentMeasurement: m.GarmentMeasurement,
		}
	}
	return defs
}

// SizingAgent researches standard garment measurements and generates diagram prompts.
type SizingAgent struct {
	braveClient *BraveSearchClient
	openRouter  sizingStructuredClient
}

// sizingStructuredClient keeps the two-call orchestration testable without
// changing the shared OpenRouter client or any public sizing APIs.
type sizingStructuredClient interface {
	CallWithSchemaAndModel(context.Context, string, map[string]interface{}, string) (*StructuredResponse, error)
}

// NewSizingAgent creates a new sizing agent instance.
func NewSizingAgent() *SizingAgent {
	return &SizingAgent{
		braveClient: NewBraveSearchClient(),
		openRouter:  NewOpenRouterStructuredClient(),
	}
}

// GenerateSizingResearch is a convenience function that uses default clients.
func GenerateSizingResearch(ctx context.Context, clothingType, styleNotes string) (*SizingAgentResult, error) {
	return GenerateSizingResearchWithModel(ctx, clothingType, styleNotes, "")
}

// GenerateSizingResearchWithModel conducts tailoring research using an optional model override.
func GenerateSizingResearchWithModel(ctx context.Context, clothingType, styleNotes, modelOverride string) (*SizingAgentResult, error) {
	agent := NewSizingAgent()
	return agent.ResearchWithModel(ctx, clothingType, styleNotes, modelOverride)
}

// UpdateDiagramPromptsWithModel updates the diagram prompts for vector and mannequin styles based on the given measurements.
func UpdateDiagramPromptsWithModel(ctx context.Context, clothingType, styleNotes string, measurements []SizingAgentMeasurement, currentVectorPrompt, currentMannequinPrompt, modelOverride string) (*DiagramPromptsResult, error) {
	agent := NewSizingAgent()
	return agent.UpdateDiagramPromptsWithModel(ctx, clothingType, styleNotes, measurements, currentVectorPrompt, currentMannequinPrompt, modelOverride)
}

// Research conducts tailoring research and returns standard measurements and diagram prompt.
func (a *SizingAgent) Research(ctx context.Context, clothingType, styleNotes string) (*SizingAgentResult, error) {
	return a.ResearchWithModel(ctx, clothingType, styleNotes, "")
}

// ResearchWithModel conducts tailoring research and returns standard measurements and diagram prompt using the given model.
func (a *SizingAgent) ResearchWithModel(ctx context.Context, clothingType, styleNotes, modelOverride string) (*SizingAgentResult, error) {
	trimmedType := strings.TrimSpace(clothingType)
	if trimmedType == "" {
		return nil, fmt.Errorf("clothing type is required")
	}

	// 1. Gather context using Brave Search if available
	searchContext := a.collectSearchContext(ctx, trimmedType)

	// 2. Resolve model: explicit override > AI settings chat_model > fallback to gpt-4o-mini
	model := ResolveModel(strings.TrimSpace(modelOverride), ResolveModel(ChatModelOverride(ctx), "openai/gpt-4o-mini"))

	// 3. Generate only the garment definitions, admin measuring instructions,
	// and diagram prompt. Keeping the buyer-facing guide out of this response
	// prevents the two audiences from being blended by the model.
	definitionsPrompt := buildSizingAgentPrompt(trimmedType, styleNotes, searchContext)
	definitionsResp, err := a.openRouter.CallWithSchemaAndModel(ctx, definitionsPrompt, sizingAgentSchema(), model)
	if err != nil {
		return nil, fmt.Errorf("failed to generate sizing definitions: %w", err)
	}

	var result SizingAgentResult
	if err := json.Unmarshal([]byte(definitionsResp.Content), &result); err != nil {
		return nil, fmt.Errorf("failed to parse sizing definitions output: %w", err)
	}

	// 4. Generate the buyer guide from an explicit, lossless representation of
	// the measurements just generated. The second schema contains only the
	// guide, so it cannot accidentally replace the definitions or diagram.
	guideInput, err := json.Marshal(sizingBuyerGuideInput{
		ClothingType: trimmedType,
		StyleNotes:   strings.TrimSpace(styleNotes),
		Name:         result.Name,
		Slug:         result.Slug,
		Measurements: result.Measurements,
	})
	if err != nil {
		return nil, fmt.Errorf("failed to prepare sizing guide input: %w", err)
	}
	guidePrompt := buildBuyerFitGuidePrompt(string(guideInput))
	guideResp, err := a.openRouter.CallWithSchemaAndModel(ctx, guidePrompt, sizingBuyerGuideSchema(), model)
	if err != nil {
		return nil, fmt.Errorf("failed to generate buyer sizing guide: %w", err)
	}

	var guide sizingBuyerGuideOutput
	if err := json.Unmarshal([]byte(guideResp.Content), &guide); err != nil {
		return nil, fmt.Errorf("failed to parse buyer sizing guide output: %w", err)
	}
	result.GeneralFitGuide = guide.GeneralFitGuide

	// Maintain vector/mannequin aliases and legacy fallback logic
	if result.ImagePromptVector == "" {
		result.ImagePromptVector = result.NanoBananaPrompt
	}
	if result.NanoBananaPrompt == "" {
		result.NanoBananaPrompt = result.ImagePromptVector
	}
	if result.ImagePrompt == "" {
		result.ImagePrompt = result.ImagePromptVector
	}

	return &result, nil
}

// UpdateDiagramPromptsWithModel updates the diagram prompts for vector and mannequin styles so they describe only the provided measurements.
func (a *SizingAgent) UpdateDiagramPromptsWithModel(ctx context.Context, clothingType, styleNotes string, measurements []SizingAgentMeasurement, currentVectorPrompt, currentMannequinPrompt, modelOverride string) (*DiagramPromptsResult, error) {
	if len(measurements) == 0 {
		return nil, fmt.Errorf("at least one measurement is required")
	}

	model := ResolveModel(strings.TrimSpace(modelOverride), ResolveModel(ChatModelOverride(ctx), "openai/gpt-4o-mini"))

	prompt := buildUpdateDiagramPromptsPrompt(clothingType, styleNotes, measurements, currentVectorPrompt, currentMannequinPrompt)
	resp, err := a.openRouter.CallWithSchemaAndModel(ctx, prompt, diagramPromptsSchema(), model)
	if err == nil {
		var result DiagramPromptsResult
		if unmarshalErr := json.Unmarshal([]byte(resp.Content), &result); unmarshalErr == nil && result.ImagePromptVector != "" && result.ImagePromptMannequin != "" {
			return &result, nil
		}
	}

	// Fallback logic: construct standard prompts templates using the style blocks and measurements
	return buildFallbackDiagramPrompts(clothingType, styleNotes, measurements), nil
}

func buildFallbackDiagramPrompts(clothingType, styleNotes string, measurements []SizingAgentMeasurement) *DiagramPromptsResult {
	garmentDesc := strings.TrimSpace(clothingType)
	if garmentDesc == "" {
		garmentDesc = "garment"
	}
	if strings.TrimSpace(styleNotes) != "" {
		garmentDesc = fmt.Sprintf("%s (%s)", garmentDesc, strings.TrimSpace(styleNotes))
	}

	var vectorLines strings.Builder
	var mannequinLines strings.Builder

	for i, m := range measurements {
		label := strings.TrimSpace(m.Label)
		if label == "" {
			label = m.Key
		}
		num := i + 1
		vectorLines.WriteString(fmt.Sprintf("%d. A dimension line indicating %s, labeled \"%s\"\n", num, m.Key, label))
		mannequinLines.WriteString(fmt.Sprintf("%d. An elegant dimension line indicating %s, labeled \"%s\"\n", num, m.Key, label))
	}

	vectorPrompt := fmt.Sprintf("%s\n\nThe garment is a %s. Draw exactly %d dimension lines with these exact Persian labels:\n%s",
		sizeGuideVectorDiagramStyleBlock,
		garmentDesc,
		len(measurements),
		strings.TrimRight(vectorLines.String(), "\n"),
	)

	mannequinPrompt := fmt.Sprintf("%s\n\nThe garment is a photorealistic luxury %s with authentic tailoring details. Place exactly %d elegant dimension lines with these exact Persian labels:\n%s",
		sizeGuideMannequinDiagramStyleBlock,
		garmentDesc,
		len(measurements),
		strings.TrimRight(mannequinLines.String(), "\n"),
	)

	return &DiagramPromptsResult{
		ImagePromptVector:    vectorPrompt,
		ImagePromptMannequin: mannequinPrompt,
	}
}

func diagramPromptsSchema() map[string]interface{} {
	return map[string]interface{}{
		"name":   "sizing_diagram_prompts_output",
		"strict": true,
		"schema": map[string]interface{}{
			"type":                 "object",
			"additionalProperties": false,
			"properties": map[string]interface{}{
				"image_prompt_vector": map[string]interface{}{
					"type":        "string",
					"description": "English prompt for technical flat sketch vector line art diagram on warm off-white background (#FAF7F2), with exact numbered Persian labels matching the remaining measurements",
				},
				"image_prompt_mannequin": map[string]interface{}{
					"type":        "string",
					"description": "English prompt for realistic 3D invisible ghost mannequin studio product photography on pure white background (#FFFFFF) with Voxcina luxury aesthetic and exact numbered Persian labels matching the remaining measurements",
				},
			},
			"required": []string{"image_prompt_vector", "image_prompt_mannequin"},
		},
	}
}

func buildUpdateDiagramPromptsPrompt(clothingType, styleNotes string, measurements []SizingAgentMeasurement, currentVectorPrompt, currentMannequinPrompt string) string {
	measurementsJSON, _ := json.MarshalIndent(measurements, "", "  ")

	return fmt.Sprintf(`You are an expert master fashion pattern maker, garment sizing specialist, and technical illustrator for an Iranian e-commerce fashion brand.

Clothing Type: %s
Style & Fit Notes: %s

Current Remaining Measurements (%d items):
%s

Current Vector Diagram Prompt (if any):
%s

Current Mannequin Diagram Prompt (if any):
%s

Your task is to update or regenerate the two diagram image generator prompts so they describe ONLY the remaining measurements above:
1. "image_prompt_vector": English prompt for technical flat sketch vector line art diagram.
   It MUST strictly follow this exact format:
   First, paste the vector style block verbatim:
   "%s"
   Then, describe the garment silhouette clearly, and list numbered dimension lines 1..%d with their exact Persian labels in quotes matching ONLY the remaining measurements:
   "The garment is a [silhouette description]. Draw exactly %d dimension lines with these exact Persian labels:
   1. A [orientation] line along [location], labeled \"[Exact Persian Label]\"
   2. ... "

2. "image_prompt_mannequin": English prompt for realistic 3D invisible ghost mannequin studio product photography on pure white background (#FFFFFF).
   It MUST strictly follow this exact format:
   First, paste the mannequin style block verbatim:
   "%s"
   Then, describe the real garment matching the style and fit, and list numbered dimension lines 1..%d with their exact Persian labels in quotes matching ONLY the remaining measurements:
   "The garment is a [photorealistic garment description]. Place exactly %d elegant dimension lines with these exact Persian labels:
   1. A [orientation] line along [location], labeled \"[Exact Persian Label]\"
   2. ... "

Do NOT include any deleted or previous measurements. Renumber all dimension lines consecutively from 1 to %d.
Return valid JSON matching the schema.`,
		clothingType,
		styleNotes,
		len(measurements),
		string(measurementsJSON),
		currentVectorPrompt,
		currentMannequinPrompt,
		sizeGuideVectorDiagramStyleBlock,
		len(measurements),
		len(measurements),
		sizeGuideMannequinDiagramStyleBlock,
		len(measurements),
		len(measurements),
		len(measurements),
	)
}

type sizingBuyerGuideInput struct {
	ClothingType string                   `json:"clothing_type"`
	StyleNotes   string                   `json:"style_notes,omitempty"`
	Name         string                   `json:"name"`
	Slug         string                   `json:"slug"`
	Measurements []SizingAgentMeasurement `json:"measurements"`
}

type sizingBuyerGuideOutput struct {
	GeneralFitGuide string `json:"general_fit_guide"`
}

func (a *SizingAgent) collectSearchContext(ctx context.Context, clothingType string) string {
	if a.braveClient == nil || !a.braveClient.IsAvailable() {
		return "No search engine available. Rely on standard tailoring knowledge."
	}

	searchCtx, cancel := context.WithTimeout(ctx, 10*time.Second)
	defer cancel()

	var snippets []string

	// Search Persian tailoring guides
	faQuery := fmt.Sprintf("%s راهنمای اندازه گیری و جدول سایز لباس استاندارد خیاطی", clothingType)
	if faResults, err := a.braveClient.SearchWeb(searchCtx, faQuery, SearchOptions{Count: 3}); err == nil {
		for _, r := range faResults {
			if r.Snippet != "" {
				snippets = append(snippets, fmt.Sprintf("- [%s]: %s", r.Title, r.Snippet))
			}
		}
	}

	// Search English tailoring guides
	enQuery := fmt.Sprintf("%s garment measurement guide standard tailoring size chart", clothingType)
	if enResults, err := a.braveClient.SearchWeb(searchCtx, enQuery, SearchOptions{Count: 3}); err == nil {
		for _, r := range enResults {
			if r.Snippet != "" {
				snippets = append(snippets, fmt.Sprintf("- [%s]: %s", r.Title, r.Snippet))
			}
		}
	}

	if len(snippets) == 0 {
		return "No external tailoring search results found."
	}
	return strings.Join(snippets, "\n")
}

func sizingAgentSchema() map[string]interface{} {
	return map[string]interface{}{
		"name":   "sizing_definitions_output",
		"strict": true,
		"schema": map[string]interface{}{
			"type": "object",
			"properties": map[string]interface{}{
				"name": map[string]interface{}{
					"type":        "string",
					"description": "Descriptive Persian name for this clothing sizing type, e.g. کت بلیزر زنانه",
				},
				"slug": map[string]interface{}{
					"type":        "string",
					"description": "URL-safe English kebab-case slug, e.g. women-blazer",
				},
				"measurements": map[string]interface{}{
					"type":        "array",
					"description": "5 to 6 essential standard garment measurements for this clothing type",
					"items": map[string]interface{}{
						"type": "object",
						"properties": map[string]interface{}{
							"key": map[string]interface{}{
								"type":        "string",
								"description": "English snake_case key (e.g. chest_width, total_length, shoulder_width, sleeve_length, waist, hip, inseam)",
							},
							"label": map[string]interface{}{
								"type":        "string",
								"description": "Standard Persian label for this measurement (e.g. عرض سینه, قد لباس, عرض شانه, قد آستین, دور کمر)",
							},
							"body_guide": map[string]interface{}{
								"type":        "string",
								"description": "Clear step-by-step Persian instructions on how and where to measure with tape on the human body",
							},
							"fit_advice": map[string]interface{}{
								"type":        "string",
								"description": "Persian advice explaining ease allowance and how flat garment measurement compares to body circumference",
							},
							"garment_measurement": map[string]interface{}{
								"type":        "string",
								"description": "Concise Persian instruction for an administrator measuring this point on the laid-flat garment or size table, including whether it is flat width, circumference, or a length",
							},
						},
						"required":             []string{"key", "label", "body_guide", "fit_advice", "garment_measurement"},
						"additionalProperties": false,
					},
				},
				"admin_measurement_guide": map[string]interface{}{
					"type":        "string",
					"description": "Concise Persian guide for an administrator to lay out the garment, use the size table, and record each listed garment measurement consistently",
				},
				"nano_banana_prompt": map[string]interface{}{
					"type":        "string",
					"description": "English prompt for Nano Banana Pro diagram image generator featuring technical flat sketch vector line art on warm off-white background (#FAF7F2), including exact Persian labels in quotes",
				},
				"image_prompt_vector": map[string]interface{}{
					"type":        "string",
					"description": "English prompt for technical flat sketch vector line art diagram on warm off-white background (#FAF7F2), matching nano_banana_prompt",
				},
				"image_prompt_mannequin": map[string]interface{}{
					"type":        "string",
					"description": "English prompt for realistic 3D invisible ghost mannequin studio product photography on pure white background (#FFFFFF) with Voxcina luxury aesthetic and exact Persian labels in quotes",
				},
			},
			"required":             []string{"name", "slug", "measurements", "admin_measurement_guide", "nano_banana_prompt", "image_prompt_mannequin"},
			"additionalProperties": false,
		},
	}
}

func buildSizingAgentPrompt(clothingType, styleNotes, searchContext string) string {
	notesSection := "None"
	if strings.TrimSpace(styleNotes) != "" {
		notesSection = styleNotes
	}

	return fmt.Sprintf(`You are an expert master fashion pattern maker, garment sizing specialist, and technical illustrator for an Iranian e-commerce fashion brand.

Clothing Type: %s
Style & Fit Notes: %s

Search & Tailoring Context:
%s

Your task is ONLY to create garment measurement definitions, admin production guidance, and two distinct diagram image generator prompts. Do not write a buyer-facing general fit guide or a field named "general_fit_guide"; that will be generated in a separate second call.
1. Provide a concise, professional Persian display name (name) and an English kebab-case slug (slug).
2. Define exactly 5 to 6 essential measurements that buyers need when purchasing this specific garment.
   For each measurement:
   - "key": concise English snake_case identifier (e.g. chest, waist, sleeve_length, shoulder, total_length, hip, inseam).
   - "label": precise Persian standard tailoring term (e.g. "عرض سینه", "دور کمر", "قد آستین", "عرض شانه", "قد کل").
   - "body_guide": clear, polite Persian guide explaining exactly where to place the tape measure on the body and how to measure (نحوه اندازه‌گیری روی بدن).
   - "fit_advice": practical Persian advice on ease allowance (آزادی لباس), fit differences (e.g. difference between flat garment width and body circumference, loose vs fitted).
   - "garment_measurement": concise Persian instruction for an administrator measuring the physical garment or maintaining the size table. State the exact garment points and whether the value is a flat width, a circumference, or a length; do not confuse this with measuring a person's body.
3. "admin_measurement_guide": a concise Persian guide for laying the garment flat, measuring consistently, and entering the listed values in a size table. This is for administrators, not buyers.
4. "nano_banana_prompt" (and identical "image_prompt_vector"): an English prompt for generating a technical flat sketch vector diagram.
   It MUST strictly follow this exact format:
   First, paste the vector style block verbatim:
   "%s"
   Then, describe the garment silhouette clearly, and list numbered dimension lines with their exact Persian labels in quotes matching the labels in measurements, e.g.:
   "The garment is a [silhouette description]. Draw exactly [N] dimension lines with these exact Persian labels:
   1. A [orientation] line along [location], labeled \"[Exact Persian Label]\"
   2. ... "
5. "image_prompt_mannequin": an English prompt for generating a realistic 3D invisible ghost mannequin product photography diagram on a pure white background.
   It MUST strictly follow this exact format:
   First, paste the mannequin style block verbatim:
   "%s"
   Then, describe the real garment matching the style, cut, fit, tailoring folds, and details, and list numbered dimension lines with their exact Persian labels in quotes matching the labels in measurements, e.g.:
   "The garment is a [photorealistic garment and tailoring description]. Place exactly [N] elegant dimension lines with these exact Persian labels:
   1. A [orientation] line along [location], labeled \"[Exact Persian Label]\"
   2. ... "

Ensure Persian text is written with correct Persian typography and orthography (نیم‌فاصله).
Return valid JSON matching the schema.`,
		clothingType,
		notesSection,
		searchContext,
		sizeGuideVectorDiagramStyleBlock,
		sizeGuideMannequinDiagramStyleBlock,
	)
}

func sizingBuyerGuideSchema() map[string]interface{} {
	return map[string]interface{}{
		"name":   "sizing_buyer_guide_output",
		"strict": true,
		"schema": map[string]interface{}{
			"type":                 "object",
			"additionalProperties": false,
			"properties": map[string]interface{}{
				"general_fit_guide": map[string]interface{}{
					"type":        "string",
					"description": "Natural, fluent, and highly understandable Persian buyer guide in exactly one short, cohesive paragraph of a couple of sentences (حداکثر ۲ تا ۴ جمله روان). Thorough advice summarizing how the garment is meant to fit on the body, fabric drape/stretch considerations, ease behavior, specific fit criteria, and tips for choosing between two sizes without measurement instructions.",
				},
			},
			"required": []string{"general_fit_guide"},
		},
	}
}

func buildBuyerFitGuidePrompt(measurementsJSON string) string {
	return fmt.Sprintf(`You are an expert master fashion pattern maker and garment sizing specialist for an Iranian premium fashion e-commerce brand.

The following JSON is the exact output of the garment-definition step, including garment details, style notes, and measurement definitions. Preserve every measurement key and Persian label conceptually; do not invent, remove, rename, or reorder the measurements:
<EXACT_GENERATED_MEASUREMENTS>
%s
</EXACT_GENERATED_MEASUREMENTS>

Write ONLY the value of "general_fit_guide" in natural, fluent, and highly understandable Persian for buyers.
- Write thorough Persian advice summarizing how this garment is meant to fit, fabric drape/stretch considerations, sizing recommendations between two sizes, and styling notes.
- Keep it to exactly ONE short, cohesive paragraph consisting of only a couple of sentences (حداکثر ۲ تا ۴ جمله روان).
- Focus on how the garment sits and fits on the body (ایستایی و تن‌خور لباس روی اندام), its ease and drape behavior, its specific fit criteria/features, and tips for choosing between two sizes when applicable.
- Use correct Persian typography and orthography (رعایت نیم‌فاصله).
- Do NOT produce bullet points, numbered lists, headings, tape-measure instructions, or long explanations.
- Do not give administrator instructions, production instructions, a diagram prompt, JSON, or unrelated text.
Return valid JSON matching the schema.`, measurementsJSON)
}
