package services

import (
	"context"
	"encoding/json"
	"fmt"
	"strings"
	"time"

	"backEnd/models"
)

const sizeGuideDiagramStyleBlock = `Minimalist premium fashion size-guide diagram. Technical flat sketch of the garment, front view, centered, on a warm off-white background (#FAF7F2). Thin, clean charcoal-black line art (#2B2B2B), no shading, no texture, no shadows, no model. Elegant measurement dimension lines in a single muted terracotta accent color (#C4754B) with small arrowheads at both ends, placed outside the garment silhouette. Each dimension line is labeled with its Persian measurement name in clean, legible, modern Persian typography (same terracotta color), positioned next to its line without overlapping the garment. Lots of breathing room, balanced composition, high-end boutique aesthetic. Absolutely no other text, letters, numbers, watermarks, or logos anywhere in the image.`

// SizingAgentMeasurement represents one measurement definition generated by the sizing agent.
type SizingAgentMeasurement struct {
	Key       string `json:"key"`
	Label     string `json:"label"`
	BodyGuide string `json:"body_guide"`
	FitAdvice string `json:"fit_advice"`
}

// SizingAgentResult holds the structured output returned by the sizing agent.
type SizingAgentResult struct {
	Name             string                   `json:"name"`
	Slug             string                   `json:"slug"`
	Measurements     []SizingAgentMeasurement `json:"measurements"`
	GeneralFitGuide  string                   `json:"general_fit_guide"`
	NanoBananaPrompt string                   `json:"nano_banana_prompt"`
	ImagePrompt      string                   `json:"image_prompt,omitempty"`
}

// ToMeasurementDefs converts agent measurements to model measurement definitions.
func (r *SizingAgentResult) ToMeasurementDefs() []models.SizingMeasurementDef {
	defs := make([]models.SizingMeasurementDef, len(r.Measurements))
	for i, m := range r.Measurements {
		defs[i] = models.SizingMeasurementDef{
			Key:       m.Key,
			Label:     m.Label,
			BodyGuide: m.BodyGuide,
			FitAdvice: m.FitAdvice,
		}
	}
	return defs
}

// SizingAgent researches standard garment measurements and generates diagram prompts.
type SizingAgent struct {
	braveClient *BraveSearchClient
	openRouter  *OpenRouterStructuredClient
}

// NewSizingAgent creates a new sizing agent instance.
func NewSizingAgent() *SizingAgent {
	return &SizingAgent{
		braveClient: NewBraveSearchClient(),
		openRouter:  NewOpenRouterStructuredClient(),
	}
}

// GenerateSizingResearch is a convenience function that uses default clients.
func GenerateSizingResearch(ctx context.Context, clothingType, styleNotes string) (*SizingAgentResult, error) {
	return GenerateSizingResearchWithModel(ctx, clothingType, styleNotes, "")
}

// GenerateSizingResearchWithModel conducts tailoring research using an optional model override.
func GenerateSizingResearchWithModel(ctx context.Context, clothingType, styleNotes, modelOverride string) (*SizingAgentResult, error) {
	agent := NewSizingAgent()
	return agent.ResearchWithModel(ctx, clothingType, styleNotes, modelOverride)
}

// Research conducts tailoring research and returns standard measurements and diagram prompt.
func (a *SizingAgent) Research(ctx context.Context, clothingType, styleNotes string) (*SizingAgentResult, error) {
	return a.ResearchWithModel(ctx, clothingType, styleNotes, "")
}

// ResearchWithModel conducts tailoring research and returns standard measurements and diagram prompt using the given model.
func (a *SizingAgent) ResearchWithModel(ctx context.Context, clothingType, styleNotes, modelOverride string) (*SizingAgentResult, error) {
	trimmedType := strings.TrimSpace(clothingType)
	if trimmedType == "" {
		return nil, fmt.Errorf("clothing type is required")
	}

	// 1. Gather context using Brave Search if available
	searchContext := a.collectSearchContext(ctx, trimmedType)

	// 2. Resolve model: explicit override > AI settings chat_model > fallback to gpt-4o-mini
	model := ResolveModel(strings.TrimSpace(modelOverride), ResolveModel(ChatModelOverride(ctx), "openai/gpt-4o-mini"))

	// 3. Build schema and prompt
	schema := sizingAgentSchema()
	prompt := buildSizingAgentPrompt(trimmedType, styleNotes, searchContext)

	// 4. Request structured output
	resp, err := a.openRouter.CallWithSchemaAndModel(ctx, prompt, schema, model)
	if err != nil {
		return nil, fmt.Errorf("failed to generate sizing research: %w", err)
	}

	var result SizingAgentResult
	if err := json.Unmarshal([]byte(resp.Content), &result); err != nil {
		return nil, fmt.Errorf("failed to parse sizing research output: %w", err)
	}

	// Set ImagePrompt alias for convenience
	result.ImagePrompt = result.NanoBananaPrompt

	return &result, nil
}

func (a *SizingAgent) collectSearchContext(ctx context.Context, clothingType string) string {
	if a.braveClient == nil || !a.braveClient.IsAvailable() {
		return "No search engine available. Rely on standard tailoring knowledge."
	}

	searchCtx, cancel := context.WithTimeout(ctx, 10*time.Second)
	defer cancel()

	var snippets []string

	// Search Persian tailoring guides
	faQuery := fmt.Sprintf("%s راهنمای اندازه گیری و جدول سایز لباس استاندارد خیاطی", clothingType)
	if faResults, err := a.braveClient.SearchWeb(searchCtx, faQuery, SearchOptions{Count: 3}); err == nil {
		for _, r := range faResults {
			if r.Snippet != "" {
				snippets = append(snippets, fmt.Sprintf("- [%s]: %s", r.Title, r.Snippet))
			}
		}
	}

	// Search English tailoring guides
	enQuery := fmt.Sprintf("%s garment measurement guide standard tailoring size chart", clothingType)
	if enResults, err := a.braveClient.SearchWeb(searchCtx, enQuery, SearchOptions{Count: 3}); err == nil {
		for _, r := range enResults {
			if r.Snippet != "" {
				snippets = append(snippets, fmt.Sprintf("- [%s]: %s", r.Title, r.Snippet))
			}
		}
	}

	if len(snippets) == 0 {
		return "No external tailoring search results found."
	}
	return strings.Join(snippets, "\n")
}

func sizingAgentSchema() map[string]interface{} {
	return map[string]interface{}{
		"name":   "sizing_research_output",
		"strict": true,
		"schema": map[string]interface{}{
			"type": "object",
			"properties": map[string]interface{}{
				"name": map[string]interface{}{
					"type":        "string",
					"description": "Descriptive Persian name for this clothing sizing type, e.g. کت بلیزر زنانه",
				},
				"slug": map[string]interface{}{
					"type":        "string",
					"description": "URL-safe English kebab-case slug, e.g. women-blazer",
				},
				"measurements": map[string]interface{}{
					"type":        "array",
					"description": "5 to 6 essential standard garment measurements for this clothing type",
					"items": map[string]interface{}{
						"type": "object",
						"properties": map[string]interface{}{
							"key": map[string]interface{}{
								"type":        "string",
								"description": "English snake_case key (e.g. chest_width, total_length, shoulder_width, sleeve_length, waist, hip, inseam)",
							},
							"label": map[string]interface{}{
								"type":        "string",
								"description": "Standard Persian label for this measurement (e.g. عرض سینه, قد لباس, عرض شانه, قد آستین, دور کمر)",
							},
							"body_guide": map[string]interface{}{
								"type":        "string",
								"description": "Clear step-by-step Persian instructions on how and where to measure with tape on the human body",
							},
							"fit_advice": map[string]interface{}{
								"type":        "string",
								"description": "Persian advice explaining ease allowance and how flat garment measurement compares to body circumference",
							},
						},
						"required":             []string{"key", "label", "body_guide", "fit_advice"},
						"additionalProperties": false,
					},
				},
				"general_fit_guide": map[string]interface{}{
					"type":        "string",
					"description": "Comprehensive Persian advice on how this garment should fit, fabric drape/stretch considerations, and sizing tips",
				},
				"nano_banana_prompt": map[string]interface{}{
					"type":        "string",
					"description": "English prompt for Nano Banana Pro diagram image generator including exact Persian labels in quotes",
				},
			},
			"required":             []string{"name", "slug", "measurements", "general_fit_guide", "nano_banana_prompt"},
			"additionalProperties": false,
		},
	}
}

func buildSizingAgentPrompt(clothingType, styleNotes, searchContext string) string {
	notesSection := "None"
	if strings.TrimSpace(styleNotes) != "" {
		notesSection = styleNotes
	}

	return fmt.Sprintf(`You are an expert master fashion pattern maker, garment sizing specialist, and technical illustrator for an Iranian e-commerce fashion brand.

Clothing Type: %s
Style & Fit Notes: %s

Search & Tailoring Context:
%s

Your task:
1. Provide a concise, professional Persian display name (name) and an English kebab-case slug (slug).
2. Define exactly 5 to 6 essential measurements that buyers need when purchasing this specific garment.
   For each measurement:
   - "key": concise English snake_case identifier (e.g. chest, waist, sleeve_length, shoulder, total_length, hip, inseam).
   - "label": precise Persian standard tailoring term (e.g. "عرض سینه", "دور کمر", "قد آستین", "عرض شانه", "قد کل").
   - "body_guide": clear, polite Persian guide explaining exactly where to place the tape measure on the body and how to measure (نحوه اندازه‌گیری روی بدن).
   - "fit_advice": practical Persian advice on ease allowance (آزادی لباس), fit differences (e.g. difference between flat garment width and body circumference, loose vs fitted).
3. "general_fit_guide": thorough Persian advice summarizing how this garment is meant to fit, sizing recommendations between two sizes, and styling notes.
4. "nano_banana_prompt": an English prompt for generating a technical measurement diagram using Nano Banana Pro.
   It MUST strictly follow this exact format:
   First, paste the shared style block verbatim:
   "%s"
   Then, describe the garment silhouette clearly, and list numbered dimension lines with their exact Persian labels in quotes matching the labels in measurements, e.g.:
   "The garment is a [silhouette description]. Draw exactly [N] dimension lines with these exact Persian labels:
   1. A [orientation] line along [location], labeled \"[Exact Persian Label]\"
   2. ... "

Ensure Persian text is written with correct Persian typography and orthography (نیم‌فاصله).
Return valid JSON matching the schema.`,
		clothingType,
		notesSection,
		searchContext,
		sizeGuideDiagramStyleBlock,
	)
}
