package main

import (
	"context"
	"log"
	"time"

	"go.mongodb.org/mongo-driver/bson/primitive"

	"backEnd/config"
	"backEnd/db"
	"backEnd/models"
)

// SeedVocabularyMappings populates the vocabulary_mappings collection with Persian-English mappings
// This allows the AI agent to understand Persian product queries and map them to database values
func main() {
	// Load configuration
	cfg := config.LoadConfig()

	// Connect to database
	database := db.Connect(cfg)
	vocabCollection := database.Collection("vocabulary_mappings")
	ctx := context.Background()

	log.Println("Starting vocabulary mappings seed...")

	// ===== COLOR MAPPINGS =====
	colorMappings := []models.VocabularyMapping{
		{
			ID:            primitive.NewObjectID(),
			Type:          "color",
			PersianTerms:  []string{"قرمز", "سرخ", "اخرایی", "گلی"},
			EnglishTerms:  []string{"red", "crimson", "scarlet"},
			StandardValue: "red",
			Category:      "warm_colors",
			RelatedTerms:  []string{"صورتی", "نارنجی"},
			UsageCount:    0,
			CreatedAt:     time.Now(),
			UpdatedAt:     time.Now(),
		},
		{
			ID:            primitive.NewObjectID(),
			Type:          "color",
			PersianTerms:  []string{"آبی", "آبی آسمانی", "آبی تیره", "لاجوردی"},
			EnglishTerms:  []string{"blue", "sky blue", "navy", "azure"},
			StandardValue: "blue",
			Category:      "cool_colors",
			RelatedTerms:  []string{"فیروزه‌ای", "نیلی"},
			UsageCount:    0,
			CreatedAt:     time.Now(),
			UpdatedAt:     time.Now(),
		},
		{
			ID:            primitive.NewObjectID(),
			Type:          "color",
			PersianTerms:  []string{"سبز", "سبز روشن", "سبز تیره", "یشمی"},
			EnglishTerms:  []string{"green", "light green", "dark green", "emerald"},
			StandardValue: "green",
			Category:      "cool_colors",
			RelatedTerms:  []string{"زیتونی", "فیروزه‌ای"},
			UsageCount:    0,
			CreatedAt:     time.Now(),
			UpdatedAt:     time.Now(),
		},
		{
			ID:            primitive.NewObjectID(),
			Type:          "color",
			PersianTerms:  []string{"مشکی", "سیاه", "تیره"},
			EnglishTerms:  []string{"black", "dark"},
			StandardValue: "black",
			Category:      "neutral_colors",
			RelatedTerms:  []string{"خاکستری تیره", "دودی"},
			UsageCount:    0,
			CreatedAt:     time.Now(),
			UpdatedAt:     time.Now(),
		},
		{
			ID:            primitive.NewObjectID(),
			Type:          "color",
			PersianTerms:  []string{"سفید", "شیری", "استخوانی"},
			EnglishTerms:  []string{"white", "off-white", "ivory", "cream"},
			StandardValue: "white",
			Category:      "neutral_colors",
			RelatedTerms:  []string{"کرم", "بژ روشن"},
			UsageCount:    0,
			CreatedAt:     time.Now(),
			UpdatedAt:     time.Now(),
		},
		{
			ID:            primitive.NewObjectID(),
			Type:          "color",
			PersianTerms:  []string{"خاکستری", "طوسی", "دودی", "نقره‌ای"},
			EnglishTerms:  []string{"gray", "grey", "silver", "smoke"},
			StandardValue: "gray",
			Category:      "neutral_colors",
			RelatedTerms:  []string{"مشکی", "سفید"},
			UsageCount:    0,
			CreatedAt:     time.Now(),
			UpdatedAt:     time.Now(),
		},
		{
			ID:            primitive.NewObjectID(),
			Type:          "color",
			PersianTerms:  []string{"قهوه‌ای", "شکلاتی", "عسلی", "گردویی"},
			EnglishTerms:  []string{"brown", "chocolate", "tan", "walnut"},
			StandardValue: "brown",
			Category:      "warm_colors",
			RelatedTerms:  []string{"بژ", "کرم"},
			UsageCount:    0,
			CreatedAt:     time.Now(),
			UpdatedAt:     time.Now(),
		},
		{
			ID:            primitive.NewObjectID(),
			Type:          "color",
			PersianTerms:  []string{"صورتی", "گلبهی", "صورتی روشن", "هلویی"},
			EnglishTerms:  []string{"pink", "rose", "light pink", "peach"},
			StandardValue: "pink",
			Category:      "warm_colors",
			RelatedTerms:  []string{"قرمز", "بنفش"},
			UsageCount:    0,
			CreatedAt:     time.Now(),
			UpdatedAt:     time.Now(),
		},
		{
			ID:            primitive.NewObjectID(),
			Type:          "color",
			PersianTerms:  []string{"زرد", "طلایی", "زردلیمویی", "کهربایی"},
			EnglishTerms:  []string{"yellow", "gold", "lemon", "amber"},
			StandardValue: "yellow",
			Category:      "warm_colors",
			RelatedTerms:  []string{"نارنجی", "کرم"},
			UsageCount:    0,
			CreatedAt:     time.Now(),
			UpdatedAt:     time.Now(),
		},
		{
			ID:            primitive.NewObjectID(),
			Type:          "color",
			PersianTerms:  []string{"نارنجی", "پرتقالی", "نارنجی سوخته"},
			EnglishTerms:  []string{"orange", "burnt orange"},
			StandardValue: "orange",
			Category:      "warm_colors",
			RelatedTerms:  []string{"قرمز", "زرد"},
			UsageCount:    0,
			CreatedAt:     time.Now(),
			UpdatedAt:     time.Now(),
		},
		{
			ID:            primitive.NewObjectID(),
			Type:          "color",
			PersianTerms:  []string{"بنفش", "ارغوانی", "یاسی", "بادمجانی"},
			EnglishTerms:  []string{"purple", "violet", "lavender", "plum"},
			StandardValue: "purple",
			Category:      "cool_colors",
			RelatedTerms:  []string{"آبی", "صورتی"},
			UsageCount:    0,
			CreatedAt:     time.Now(),
			UpdatedAt:     time.Now(),
		},
	}

	// ===== MATERIAL MAPPINGS =====
	materialMappings := []models.VocabularyMapping{
		{
			ID:            primitive.NewObjectID(),
			Type:          "material",
			PersianTerms:  []string{"پنبه", "نخی", "کتان", "پنبه‌ای"},
			EnglishTerms:  []string{"cotton", "cotton blend"},
			StandardValue: "cotton",
			Category:      "natural_fabric",
			RelatedTerms:  []string{"نخ", "طبیعی"},
			UsageCount:    0,
			CreatedAt:     time.Now(),
			UpdatedAt:     time.Now(),
		},
		{
			ID:            primitive.NewObjectID(),
			Type:          "material",
			PersianTerms:  []string{"پشم", "پشمی", "کشمیر", "موهر"},
			EnglishTerms:  []string{"wool", "cashmere", "mohair"},
			StandardValue: "wool",
			Category:      "natural_fabric",
			RelatedTerms:  []string{"گرم", "زمستانی"},
			UsageCount:    0,
			CreatedAt:     time.Now(),
			UpdatedAt:     time.Now(),
		},
		{
			ID:            primitive.NewObjectID(),
			Type:          "material",
			PersianTerms:  []string{"ابریشم", "ابریشمی", "ساتن"},
			EnglishTerms:  []string{"silk", "satin", "silky"},
			StandardValue: "silk",
			Category:      "luxury_fabric",
			RelatedTerms:  []string{"لوکس", "نرم"},
			UsageCount:    0,
			CreatedAt:     time.Now(),
			UpdatedAt:     time.Now(),
		},
		{
			ID:            primitive.NewObjectID(),
			Type:          "material",
			PersianTerms:  []string{"پلی استر", "سنتتیک", "مصنوعی"},
			EnglishTerms:  []string{"polyester", "synthetic"},
			StandardValue: "polyester",
			Category:      "synthetic_fabric",
			RelatedTerms:  []string{"ورزشی", "سریع خشک"},
			UsageCount:    0,
			CreatedAt:     time.Now(),
			UpdatedAt:     time.Now(),
		},
		{
			ID:            primitive.NewObjectID(),
			Type:          "material",
			PersianTerms:  []string{"جین", "دنیم", "جین کشی"},
			EnglishTerms:  []string{"denim", "jeans", "jean"},
			StandardValue: "denim",
			Category:      "heavy_fabric",
			RelatedTerms:  []string{"پنبه", "محکم"},
			UsageCount:    0,
			CreatedAt:     time.Now(),
			UpdatedAt:     time.Now(),
		},
		{
			ID:            primitive.NewObjectID(),
			Type:          "material",
			PersianTerms:  []string{"چرم", "چرمی", "چرم مصنوعی", "پوست"},
			EnglishTerms:  []string{"leather", "faux leather", "PU leather"},
			StandardValue: "leather",
			Category:      "leather_fabric",
			RelatedTerms:  []string{"جیر", "کیف"},
			UsageCount:    0,
			CreatedAt:     time.Now(),
			UpdatedAt:     time.Now(),
		},
		{
			ID:            primitive.NewObjectID(),
			Type:          "material",
			PersianTerms:  []string{"کشباف", "بافت", "نایلون کشی"},
			EnglishTerms:  []string{"knit", "stretch", "elastic"},
			StandardValue: "knit",
			Category:      "stretchy_fabric",
			RelatedTerms:  []string{"راحت", "ورزشی"},
			UsageCount:    0,
			CreatedAt:     time.Now(),
			UpdatedAt:     time.Now(),
		},
		{
			ID:            primitive.NewObjectID(),
			Type:          "material",
			PersianTerms:  []string{"مخمل", "ولور", "کروماژ"},
			EnglishTerms:  []string{"velvet", "velour"},
			StandardValue: "velvet",
			Category:      "luxury_fabric",
			RelatedTerms:  []string{"لوکس", "نرم"},
			UsageCount:    0,
			CreatedAt:     time.Now(),
			UpdatedAt:     time.Now(),
		},
	}

	// ===== STYLE MAPPINGS =====
	styleMappings := []models.VocabularyMapping{
		{
			ID:            primitive.NewObjectID(),
			Type:          "style",
			PersianTerms:  []string{"اسپرت", "ورزشی", "راحتی"},
			EnglishTerms:  []string{"sport", "sporty", "athletic", "casual"},
			StandardValue: "sport",
			Category:      "casual_style",
			RelatedTerms:  []string{"کژوال", "روزمره"},
			UsageCount:    0,
			CreatedAt:     time.Now(),
			UpdatedAt:     time.Now(),
		},
		{
			ID:            primitive.NewObjectID(),
			Type:          "style",
			PersianTerms:  []string{"رسمی", "کلاسیک", "اداری", "مجلسی"},
			EnglishTerms:  []string{"formal", "classic", "office", "business"},
			StandardValue: "formal",
			Category:      "formal_style",
			RelatedTerms:  []string{"شیک", "رسمی"},
			UsageCount:    0,
			CreatedAt:     time.Now(),
			UpdatedAt:     time.Now(),
		},
		{
			ID:            primitive.NewObjectID(),
			Type:          "style",
			PersianTerms:  []string{"کژوال", "روزمره", "معمولی", "ساده"},
			EnglishTerms:  []string{"casual", "everyday", "simple"},
			StandardValue: "casual",
			Category:      "casual_style",
			RelatedTerms:  []string{"راحت", "اسپرت"},
			UsageCount:    0,
			CreatedAt:     time.Now(),
			UpdatedAt:     time.Now(),
		},
		{
			ID:            primitive.NewObjectID(),
			Type:          "style",
			PersianTerms:  []string{"مدرن", "جدید", "ترند", "مد روز"},
			EnglishTerms:  []string{"modern", "trendy", "contemporary", "fashionable"},
			StandardValue: "modern",
			Category:      "trendy_style",
			RelatedTerms:  []string{"شیک", "جوان"},
			UsageCount:    0,
			CreatedAt:     time.Now(),
			UpdatedAt:     time.Now(),
		},
		{
			ID:            primitive.NewObjectID(),
			Type:          "style",
			PersianTerms:  []string{"سنتی", "کلاسیک", "قدیمی", "محافظه کار"},
			EnglishTerms:  []string{"traditional", "classic", "vintage", "conservative"},
			StandardValue: "traditional",
			Category:      "classic_style",
			RelatedTerms:  []string{"رسمی", "قدیمی"},
			UsageCount:    0,
			CreatedAt:     time.Now(),
			UpdatedAt:     time.Now(),
		},
		{
			ID:            primitive.NewObjectID(),
			Type:          "style",
			PersianTerms:  []string{"لوکس", "شیک", "گران قیمت", "لاکچری"},
			EnglishTerms:  []string{"luxury", "elegant", "premium", "high-end"},
			StandardValue: "luxury",
			Category:      "luxury_style",
			RelatedTerms:  []string{"مجلسی", "رسمی"},
			UsageCount:    0,
			CreatedAt:     time.Now(),
			UpdatedAt:     time.Now(),
		},
		{
			ID:            primitive.NewObjectID(),
			Type:          "style",
			PersianTerms:  []string{"اور سایز", "گشاد", "بزرگ", "فری سایز"},
			EnglishTerms:  []string{"oversized", "loose", "baggy", "free size"},
			StandardValue: "oversized",
			Category:      "fit_style",
			RelatedTerms:  []string{"راحت", "کژوال"},
			UsageCount:    0,
			CreatedAt:     time.Now(),
			UpdatedAt:     time.Now(),
		},
	}

	// ===== PRODUCT TYPE MAPPINGS =====
	productTypeMappings := []models.VocabularyMapping{
		{
			ID:            primitive.NewObjectID(),
			Type:          "product_type",
			PersianTerms:  []string{"تیشرت", "تی شرت", "پیراهن آستین کوتاه"},
			EnglishTerms:  []string{"t-shirt", "tshirt", "tee"},
			StandardValue: "tshirt",
			Category:      "tops",
			RelatedTerms:  []string{"پیراهن", "بلوز"},
			UsageCount:    0,
			CreatedAt:     time.Now(),
			UpdatedAt:     time.Now(),
		},
		{
			ID:            primitive.NewObjectID(),
			Type:          "product_type",
			PersianTerms:  []string{"پیراهن", "شومیز", "پیرهن آستین بلند"},
			EnglishTerms:  []string{"shirt", "dress shirt", "button-up"},
			StandardValue: "shirt",
			Category:      "tops",
			RelatedTerms:  []string{"رسمی", "کژوال"},
			UsageCount:    0,
			CreatedAt:     time.Now(),
			UpdatedAt:     time.Now(),
		},
		{
			ID:            primitive.NewObjectID(),
			Type:          "product_type",
			PersianTerms:  []string{"شلوار", "شلوار پارچه‌ای"},
			EnglishTerms:  []string{"pants", "trousers"},
			StandardValue: "pants",
			Category:      "bottoms",
			RelatedTerms:  []string{"شلوار جین", "شلوار کتان"},
			UsageCount:    0,
			CreatedAt:     time.Now(),
			UpdatedAt:     time.Now(),
		},
		{
			ID:            primitive.NewObjectID(),
			Type:          "product_type",
			PersianTerms:  []string{"شلوار جین", "جین", "دنیم"},
			EnglishTerms:  []string{"jeans", "denim pants"},
			StandardValue: "jeans",
			Category:      "bottoms",
			RelatedTerms:  []string{"شلوار", "کژوال"},
			UsageCount:    0,
			CreatedAt:     time.Now(),
			UpdatedAt:     time.Now(),
		},
		{
			ID:            primitive.NewObjectID(),
			Type:          "product_type",
			PersianTerms:  []string{"کت", "کت تک", "ژاکت"},
			EnglishTerms:  []string{"jacket", "coat", "blazer"},
			StandardValue: "jacket",
			Category:      "outerwear",
			RelatedTerms:  []string{"پالتو", "بارانی"},
			UsageCount:    0,
			CreatedAt:     time.Now(),
			UpdatedAt:     time.Now(),
		},
		{
			ID:            primitive.NewObjectID(),
			Type:          "product_type",
			PersianTerms:  []string{"هودی", "سویشرت", "سوئت شرت"},
			EnglishTerms:  []string{"hoodie", "sweatshirt"},
			StandardValue: "hoodie",
			Category:      "tops",
			RelatedTerms:  []string{"اسپرت", "راحتی"},
			UsageCount:    0,
			CreatedAt:     time.Now(),
			UpdatedAt:     time.Now(),
		},
		{
			ID:            primitive.NewObjectID(),
			Type:          "product_type",
			PersianTerms:  []string{"کفش", "کفش کتانی", "کتونی"},
			EnglishTerms:  []string{"shoes", "sneakers"},
			StandardValue: "shoes",
			Category:      "footwear",
			RelatedTerms:  []string{"کتانی", "کفش ورزشی"},
			UsageCount:    0,
			CreatedAt:     time.Now(),
			UpdatedAt:     time.Now(),
		},
		{
			ID:            primitive.NewObjectID(),
			Type:          "product_type",
			PersianTerms:  []string{"پالتو", "کاپشن", "بارانی"},
			EnglishTerms:  []string{"coat", "overcoat", "raincoat"},
			StandardValue: "coat",
			Category:      "outerwear",
			RelatedTerms:  []string{"کت", "زمستانی"},
			UsageCount:    0,
			CreatedAt:     time.Now(),
			UpdatedAt:     time.Now(),
		},
		{
			ID:            primitive.NewObjectID(),
			Type:          "product_type",
			PersianTerms:  []string{"کلاه", "کپ", "کلاه کپ"},
			EnglishTerms:  []string{"hat", "cap", "beanie"},
			StandardValue: "hat",
			Category:      "accessories",
			RelatedTerms:  []string{"لوازم جانبی"},
			UsageCount:    0,
			CreatedAt:     time.Now(),
			UpdatedAt:     time.Now(),
		},
	}

	// ===== OCCASION MAPPINGS =====
	occasionMappings := []models.VocabularyMapping{
		{
			ID:            primitive.NewObjectID(),
			Type:          "occasion",
			PersianTerms:  []string{"روزمره", "روزانه", "همه روزه"},
			EnglishTerms:  []string{"everyday", "daily", "casual wear"},
			StandardValue: "everyday",
			Category:      "casual_occasion",
			RelatedTerms:  []string{"کژوال", "راحت"},
			UsageCount:    0,
			CreatedAt:     time.Now(),
			UpdatedAt:     time.Now(),
		},
		{
			ID:            primitive.NewObjectID(),
			Type:          "occasion",
			PersianTerms:  []string{"اداری", "محل کار", "سر کار"},
			EnglishTerms:  []string{"office", "work", "business"},
			StandardValue: "office",
			Category:      "formal_occasion",
			RelatedTerms:  []string{"رسمی", "کلاسیک"},
			UsageCount:    0,
			CreatedAt:     time.Now(),
			UpdatedAt:     time.Now(),
		},
		{
			ID:            primitive.NewObjectID(),
			Type:          "occasion",
			PersianTerms:  []string{"مهمانی", "جشن", "مجلسی"},
			EnglishTerms:  []string{"party", "celebration", "formal event"},
			StandardValue: "party",
			Category:      "formal_occasion",
			RelatedTerms:  []string{"رسمی", "شیک"},
			UsageCount:    0,
			CreatedAt:     time.Now(),
			UpdatedAt:     time.Now(),
		},
		{
			ID:            primitive.NewObjectID(),
			Type:          "occasion",
			PersianTerms:  []string{"ورزشی", "باشگاه", "ورزش"},
			EnglishTerms:  []string{"sport", "gym", "workout", "athletic"},
			StandardValue: "sport",
			Category:      "active_occasion",
			RelatedTerms:  []string{"اسپرت", "فعالیت"},
			UsageCount:    0,
			CreatedAt:     time.Now(),
			UpdatedAt:     time.Now(),
		},
		{
			ID:            primitive.NewObjectID(),
			Type:          "occasion",
			PersianTerms:  []string{"سفر", "گردش", "تفریح"},
			EnglishTerms:  []string{"travel", "vacation", "leisure"},
			StandardValue: "travel",
			Category:      "casual_occasion",
			RelatedTerms:  []string{"راحت", "کژوال"},
			UsageCount:    0,
			CreatedAt:     time.Now(),
			UpdatedAt:     time.Now(),
		},
	}

	// Combine all mappings
	allMappings := append(colorMappings, materialMappings...)
	allMappings = append(allMappings, styleMappings...)
	allMappings = append(allMappings, productTypeMappings...)
	allMappings = append(allMappings, occasionMappings...)

	// Insert mappings
	for _, mapping := range allMappings {
		_, err := vocabCollection.InsertOne(ctx, mapping)
		if err != nil {
			log.Printf("Error inserting vocabulary mapping '%s': %v", mapping.StandardValue, err)
		} else {
			log.Printf("✓ Inserted: %s (%s)", mapping.StandardValue, mapping.Type)
		}
	}

	log.Printf("\n✓ Vocabulary seed complete! Inserted %d mappings.", len(allMappings))
	log.Println("The AI agent can now map Persian terms to products efficiently.")
}
